import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ThemeRegistry } from "./components/Theme/ThemeRegistry";

const geistNunito = Nunito({
  variable: "--font-geist-nunito",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistNunito.variable}`}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
