import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { GlobalStyle } from "@/app/styles/globalStyles";
import { Header } from "./components/Header";

const geistNunito = Nunito({
  variable: "--font-geist-nunito",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistNunito.variable}`}>
        <GlobalStyle />

        <Header />

        {children}
      </body>
    </html>
  );
}
